added some command line parsing, new options, put convertsecs into a common file

diff --git a/findscreen b/findscreen
--- a/findscreen
+++ b/findscreen
@@ -1,49 +1,56 @@
 #! /bin/bash
-VERSION="0.1"
+source common.sh
 
-convertsecs() {
- secs=$(printf %.0f $1)
- ((h=${secs}/3600))
- ((m=(${secs}%3600)/60))
- ((s=${secs}%60))
- printf "%02d:%02d:%02d\n" $h $m $s
-}
-
-TARGETPATH="/var/tmp/findscreen"
-LIMIT=200
-if [[ "$1" == "-h" || "$1" == "--help" ]]; then
+show_help() {
 	echo "usage: findscreen [-l] screen video..."
 	echo "options:"
 	echo "    -l, --limit"
 	echo "        position (seconds) in video to stop searching for screen"
-	exit
-fi
-if [[ "$1" == "-l" || "$1" == "--limit" ]]; then
-	shift
-	if [[ $1 != *[!0-9]* ]]; then
-		LIMIT=$1
-		shift
-	else
-		echo bad limit
-		exit -1
-	fi
-fi
+}
+
+tmp_path="/var/tmp/findscreen"
+limit=200
+
+while true; do
+	case "$1" in
+		-l|--search-limit)
+			shift
+			limit="$1"
+			shift;;
+		-v|--version)
+			echo "$VERSION"
+			exit;;
+		-h|--help)
+			show_help
+			exit;;
+		-*)
+			echo "findscreen: unrecognized command $1" >&2
+			exit -1;;
+		*)
+			break;;
+	esac
+done
+
 COMPAREIMG="$1"
 shift
 INFILES=("$@")
-
-if [ ! -f "$COMPAREIMG" ] ; then
-	echo "bad screen, doesn't exist"
+if [[ $limit == *[!0-9]* ]]; then
+	echo "findscreen: bad limit"
 	exit -1
 fi
 
-if [ -d "$TARGETPATH" ]; then
-	rm -rf "$TARGETPATH/*.bmp"
-else
-	mkdir "$TARGETPATH"
+if [ ! -f "$COMPAREIMG" ] ; then
+	echo "findscreen: screen doesn't exist"
+	exit -1
 fi
-if [ ! -d "$TARGETPATH" ]; then
-	echo temporary path could not be created
+
+if [ -d "$tmp_path" ]; then
+	rm -rf "$tmp_path/*.bmp"
+else
+	mkdir "$tmp_path"
+fi
+if [ ! -d "$tmp_path" ]; then
+	echo "findscreen: temporary path could not be created"
 	exit -1
 fi
 
@@ -51,8 +58,8 @@ i=1
 
 for INFILE in "${INFILES[@]}"; do
 	printf "$INFILE:"
-	ffmpeg -i "$INFILE" -vf select='eq(pict_type\,I)' -vsync 2 -f image2 "$TARGETPATH/%05d.bmp" -loglevel debug 2>&1 | awk '{ if ($10 == "pict_type:I" || $9 == "pict_type:I") print substr($6,3); fflush(stdout)}' | while read timestamp; do
-		if (( $(echo "$timestamp > $LIMIT" | bc -l) )); then
+	ffmpeg -i "$INFILE" -vf select='eq(pict_type\,I)' -vsync 2 -f image2 "$tmp_path/%05d.bmp" -loglevel debug 2>&1 | awk '{ if ($10 == "pict_type:I" || $9 == "pict_type:I") print substr($6,3); fflush(stdout)}' | while read timestamp; do
+		if (( $(echo "$timestamp > $limit" | bc -l) )); then
 			break
 		fi
 	#	list=("$TARGETPATH/$ID"-*.bmp)
@@ -64,7 +71,7 @@ for INFILE in "${INFILES[@]}"; do
 		#echo last=$last, second_last=$second_last
 	#	file=$last
 		#mv -v "$file" "$TARGETPATH/$last_timestamp.bmp"
-		file="$(printf $TARGETPATH/%05d.bmp $i)"
+		file="$(printf $tmp_path/%05d.bmp $i)"
 		imghash="$(./hashcompare.py $COMPAREIMG $file | cut -d':' -f2)"
 		printf "%05d:%s:%02d\n" $i $timestamp $imghash
 		last_timestamp=$timestamp
